
# General config

## position
anchor=top-right
layer=top

max-visible=5
default-timeout=10000
ignore-timeout=0

## history
history=1
max-history=1000

height=500
width=800

## font
#font=cantarell 28
font=droid sans 28

## border
border-size=8
border-radius=10

## margins and padding
margin=20,20,20,0
# margin=150,20,20,0
padding=0,14,40,14

## colors

background-color=#1C2027
border-color=#62A8AC
# background-color=#2E3436d0
text-color=#ffffff
# Light theme
# background-color=#f0f0f0
# text-color=#2E3436ff
progress-color=over #62A8AC

## app specific configs

[app-name=discord]
background-color=#282b30
border-color=#7289da
border-size=4

[app-name=pamixer]
anchor=bottom-right
background-color=#1C2027
border-size=0
ignore-timeout=0
group-by=app-name
history=0
margin=175,200,175,0
progress-color=over #50858B
layer=overlay
width=300

[app-name=pamixer grouped=true]
format=<b>%s</b>\n%b

[app-name=dizi]
anchor=top-right
history=0
group-by=app-name
layer=overlay
border-size=0
progress-color=#396264

# background-color=#1D2F40E0
# anchor=top-center
# anchor=top-right
# anchor=bottom-right
# text-color=#1D2F40FF
# background-color=#F0F0F0E0
# background-color=#263238E0
# border-color=#009688DD
# border-color=#546E7ADD
# border-color=#546E7ADD
# border-color=#434F5ADD
