
# General config

## position
anchor=top-right
layer=top

max-visible=5
default-timeout=10000
ignore-timeout=1

## history
history=1
max-history=100

height=500
width=800

## font
font=cantarell 28
#font=droid sans 18

## border
border-size=2
border-radius=10

## margins and padding
margin=20,20,20,0
# margin=150,20,20,0
padding=0,14,30,14

## colors

### dark theme
background-color=#2E2634ff
border-color=#FFBA6Dff
# background-color=#2E3436d0
text-color=#ffffffff
# Light theme
# background-color=#f0f0f0f0
# text-color=#2E3436ff
progress-color=over #FFBA6D77

## app specific configs

[app-name=pamixer]
anchor=top-center
border-color=#5F941Eff
border-size=4
ignore-timeout=0
group-by=app-name
history=0
margin=200,0,200,0
progress-color=over #5F941Eff
layer=overlay
width=250

[app-name=pamixer grouped=true]
format=<b>%s</b>\n%b

# background-color=#1D2F40E0
# anchor=top-center
# anchor=top-right
# anchor=bottom-right
# text-color=#1D2F40FF
# background-color=#F0F0F0E0
# background-color=#263238E0
# border-color=#009688DD
# border-color=#546E7ADD
# border-color=#546E7ADD
# border-color=#434F5ADD
