[server]
socket = "/tmp/dizi-server-socket"

playlist = "~/.config/dizi/playlist.m3u"

on_song_change = "~/builds/config/scripts/dizi-notify.sh"

# supports alsa, jack
# audio_system = "pipewire"
audio_system = "alsa"

[server.player]
shuffle = false
repeat = true
next = true
volume = 20
