

numbered_command = false

mouse_support = false
focus_on_create = true

use_trash = true
watch_files = false
xdg_open = false
xdg_open_fork = false
case_insensitive_ext = true

[display]
# default, vsplit
mode = "default"

automatically_count_files = false
collapse_preview = true
column_ratio = [1, 4, 4]
# line_number_style = "absolute"
show_borders = true
show_hidden = false
show_icons = false
# none, absolute, relative
line_number_style = "none"

# size, mtime, user, gourp, perm. can be combined with |.
# `none` to disable, `all` to enable all
# all and none can't be combined with other options
linemode = "size"

[display.sort]
case_sensitive = false
directories_first = true
reverse = false
sort_method = "natural" 	# lexical, mtime, natural

[preview]
max_preview_size = 2097152 # 2MB
# preview_protocol = auto

# preview_script = "~/.config/joshuto/preview_file.sh"
# preview_shown_hook_script = "~/.config/joshuto/kitty/on_preview_shown.sh"
# preview_removed_hook_script = "~/.config/joshuto/kitty/on_preview_removed.sh"

[tab]
# inherit, home, root
home_page = "inherit"
