mapcommand = [
	{ keys = [ "T" ],		command = "new_tab" },
	{ keys = [ "ctrl+t" ],		command = "new_tab" },
	{ keys = [ "W" ],		command = "close_tab" },
	{ keys = [ "ctrl+w" ],		command = "close_tab" },
	{ keys = [ "q" ],		command = "close_tab" },
	{ keys = [ "Q" ],		command = "quit_to_cwd" },

	{ keys = [ "R" ],		command = "reload_dirlist" },
	{ keys = [ "z", "h" ],		command = "toggle_hidden" },
	{ keys = [ "\t" ],		command = "tab_switch 1" },
	{ keys = [ "backtab" ],		command = "tab_switch -1" },

	# arrow keys
	{ keys = [ "arrow_up" ],	command = "cursor_move_up" },
	{ keys = [ "arrow_down" ],	command = "cursor_move_down" },
	{ keys = [ "arrow_left" ],	command = "cd .." },
	{ keys = [ "arrow_right" ],	command = "open" },
	{ keys = [ "\n" ],		command = "open" },
	{ keys = [ "end" ],		command = "cursor_move_end" },
	{ keys = [ "home" ],		command = "cursor_move_home" },
	{ keys = [ "page_up" ],		command = "cursor_move_page_up" },
	{ keys = [ "page_down" ],	command = "cursor_move_page_down" },

	{ keys = [ "[" ],		command = "parent_cursor_move_up" },
	{ keys = [ "]" ],		command = "parent_cursor_move_down" },

	{ keys = [ "r" ],		command = "open_with" },

	{ keys = [ "c", "d" ],		command = ":cd " },
	{ keys = [ "d", "d" ],		command = "cut_files" },
	{ keys = [ "y", "y" ],		command = "copy_files" },
	{ keys = [ "p", "p" ],		command = "paste_files" },
	{ keys = [ "p", "o" ],		command = "paste_files --overwrite=true" },

	{ keys = [ "y", "n" ],		command = "copy_filename" },
	{ keys = [ "y", "." ],		command = "copy_filename_without_extension" },
	{ keys = [ "y", "p" ],		command = "copy_filepath" },
	{ keys = [ "y", "d" ],		command = "copy_dirpath" },

	{ keys = [ "delete" ],		command = "delete_files" },
	{ keys = [ "d", "D" ],		command = "delete_files" },

	{ keys = [ "a" ],		command = "rename_append" },
	{ keys = [ "A" ],		command = "rename_prepend" },

	{ keys = [ " " ],		command = "select --toggle=true" },
	{ keys = [ "t" ],		command = "select --all=true --toggle=true" },

	{ keys = [ "w" ],		command = "show_workers --exit-key=w" },
	{ keys = [ "b", "b" ],		command = "bulk_rename" },
	{ keys = [ "=" ],		command = "set_mode" },

	{ keys = [ ":" ],		command = ":" },
	{ keys = [ ";" ],		command = ":" },

	{ keys = [ "'" ],		command = ":shell " },
	{ keys = [ "m", "k" ],		command = ":mkdir " },
	{ keys = [ "c", "w" ],		command = ":rename " },

	{ keys = [ "/" ],		command = ":search " },
	{ keys = [ "\\" ],		command = ":search_glob " },
	{ keys = [ "?" ],		command = ":search_skim " },

	{ keys = [ "n" ],		command = "search_next" },
	{ keys = [ "N" ],		command = "search_prev" },

	{ keys = [ "s", "r" ],		command = "sort reverse" },
	{ keys = [ "s", "l" ],		command = "sort lexical" },
	{ keys = [ "s", "m" ],		command = "sort mtime" },
	{ keys = [ "s", "n" ],		command = "sort natural" },
	{ keys = [ "s", "s" ],		command = "sort size" },
	{ keys = [ "s", "e" ],		command = "sort ext" },

	# tab switching
	{ keys = [ "1" ],		command = "tab_switch_index 1" },
	{ keys = [ "2" ],		command = "tab_switch_index 2" },
	{ keys = [ "3" ],		command = "tab_switch_index 3" },
	{ keys = [ "4" ],		command = "tab_switch_index 4" },
	{ keys = [ "5" ],		command = "tab_switch_index 5" },


	# bookmarks
	{ keys = [ "g", "r" ],		command = "cd /" },
	{ keys = [ "g", "b" ],		command = "cd ~/builds" },
	{ keys = [ "g", "c" ],		command = "cd ~/.config" },
	{ keys = [ "g", "d" ],		command = "cd ~/Downloads" },
	{ keys = [ "g", "e" ],		command = "cd /etc" },
	{ keys = [ "g", "h" ],		command = "cd ~/" },
	{ keys = [ "g", "m" ],		command = "cd /run/media/kamiyaa" },
	{ keys = [ "g", "M" ],		command = "cd ~/music" },
	{ keys = [ "g", "p" ],		command = "cd ~/pictures" },
	{ keys = [ "g", "P" ],		command = "cd ~/Pictures" },
	{ keys = [ "g", "t" ],		command = "cd /tmp/kamiyaa" },
	{ keys = [ "g", "v" ],		command = "cd ~/videos" },
	{ keys = [ "g", "u" ],		command = "cd ~/documents/utsc" },
	{ keys = [ "g", "y" ],		command = "cd ~/youtube" },
]
