anchor = top-left

# font-name = "/usr/share/fonts/fira-code/FiraCode-Medium.ttf"
font-name = Fira Code
font-size = 48

num-results = 7

outline-width = 0
outline-color = #ffba6d

prompt-text = "run: "

selection-color = #78CAD2
# selection-background = #0a0c0e
text-color = #ffffff

background-color = #1C2027dd
border-color = #62A8ACff
border-width = 2
corner-radius = 12

margin-top = 20%
margin-left = 10%

padding-top = 5%
padding-bottom = 5%
padding-left = 5%
padding-right = 5%

width = 75%
height = 60%
